### PR TITLE
Changes made to fix the java 11 compiling issue

### PR DESCRIPTION
**Pull request by shivakrishnaah**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shua** [comment]
cc @chaochenq (as most prevalent committer) @yiyagong (as most recent committer)

All PR verify builds are failing, I think this PR fixes it. What do maintainers need from community to review+merge changes?

**Comment by maratxxx** [comment]
@shua, what is the issue? "I think this PR fixes it" - is this issue resolved now?

**Comment by shua** [comment]
@maratxxx currently, master branch does not build with any jdk version greater than 1.8. The verify jobs are being run with jdk version 11, thus any new pull requests will fail to verify not because there is any issue with the code in the PR, but because the master branch is no longer passing.

This PR seems to fix the issue, as it's the only PR that has passed a verify using jdk version 11 (also the changes are relevant to the issue).

**Comment by maratxxx** [comment]
Thank you @shua . We haven't tested yet if we can use javac1.7 in JDK 11. We know that we can use  javac1.7 with java 1.8.

**Comment by shua** [comment]
@maratxxx that's fine, in the meantime, can you change the travis-ci server to use java 1.8 instead of java 11, so PRs can pass automatic verification?

**Pull request closed without merging**
