### PR TITLE
Agent Fixes: Proper Log4j logging, and exits on critical errors

### PR DESCRIPTION
**Pull request by diranged**
@chaochenq,
  Sorry this PR has a few features to it .. but this is what we've been running in production for a few weeks now. This PR has two major changes.

The first is that we replace your custom (and non-overridable) log4j configuration with a more traditional log4j config. This allows people to set up their own logging levels and loggers. In our case, this actually let us implement our own https://github.com/Nextdoor/rollbar-log4j logger that forwards all exceptions to Rollbar for us.

The second change is that we're more aggressive about killing the agent entirely. You had some almost "catch all" scenarios where we could run the agent out of memory and it would continue to fail in a permanent loop. We more aggressively die when this happens now.

Finally, there were some packaging changes that make shipping this to Travis easier.

### CODE REVIEW

**Comment by chaochenq** [comment]
Thanks @diranged for doing this! According to the description, the changes make sense to me. I'll try to spend some time this week porting it to our code base, test it out, and merge it. I'll also address the metric related stuff you brought up in other issues.

Sorry for not being able to actively work on this!

**Comment by chaochenq** [comment]
Hi @diranged I'm fine with changing this back to traditional log4j config. The only concern is that if this is backward compatible. For example if people already uses agent config for log4j configuration, would this change still work for them?

**Comment by diranged** [comment]
@stlava can you comment on @chaochenq's question?

**Comment by diranged** [comment]
@chaochenq I am working on this PR as well as a bunch of other changes.. are you still actively maintaining this project, or is there anyone else I should work with?

We are working on re-packaging the app as a full "fat" JAR file with all the dependencies baked in. While we're here, we fixing the fact that none of the actual tests run at all when you call `mvn test` because of some directory structure layout issues. Finally, the log4j code here was only partially complete (which we didn't see before because the tests weren't running)... so I am finishing it up.

**Comment by chaochenq** [comment]
@diranged I can look at it. When do you need this in? I can try pulling other people in if you want to get this in ASAP, as I'm kind of focusing on other stuff now...

**Comment by diranged** [comment]
@chaochenq Ideally we would merge this PR before my next one (https://github.com/Nextdoor/amazon-kinesis-agent/pull/12) .. just to keep them logically separate. However, https://github.com/Nextdoor/amazon-kinesis-agent/pull/12 definitely depends on the log4j changes already being there.

Check out https://github.com/Nextdoor/amazon-kinesis-agent/pull/12 and let me know what you think about that as well? I think its a big cleanup and improvement that makes developing/testing the code easier. It also makes it significantly easier to run the agent on the CLI right from your build branch..

**Comment by diranged** [comment]
Oh also https://github.com/Nextdoor/amazon-kinesis-agent/pull/12 has a couple of Log4j related fixes. If you want, I could break those out and get them into this PR for you..

**Comment by chaochenq** [comment]
@diranged Ok I'll see what I can do, either myself or to pull someone else onto this

**Pull request closed without merging**
