### PR TITLE
Properly match file footers

### PR DESCRIPTION
**Pull request by frankfarrell**
Regex doesnt match correctly againt CharBuffer. The ByteBuffer needs to be converted to a String first. I have tested this by builing locally and it works.

### CODE REVIEW

**Comment by frankfarrell** [comment]
@chaochenq Would it be possible to merge this and do a release? Thanks!

**Comment by frankfarrell** [comment]
@chaochenq Would it be possible to merge this soon and release? Thanks

**Comment by chaochenq** [comment]
I just realized there's a rename from setup -> setup.sh in this commit. Any reason why that change has to be made?

**Comment by frankfarrell** [comment]
No particular reason other than that its a bash script

**Comment by diranged** [comment]
@frankfarrell I reverted that change... primarily because it did not also include a fix to the test-runner, or the user documentation.

**Comment by frankfarrell** [comment]
@diranged Thats no bother at all

**Pull request merged**
